export { default as Auth } from './Auth'
export { default as Home } from './Home'
export { default as Order } from './Order'
export { default as DelieveryRequest } from './DelieveryRequest'
export { default as Location } from './Location'
export { default as Support } from './Support'
